# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feb09c922ff190c7b31333e0da703e33af7fc2283e613b9bbb48a6c0c1bd5b0f60b3a94ec7c72c43153ac9e7189809a202dedd5ddcad603cec9858277d25b7a4

test:
  secret_key_base: dd878ca5b6b6e94dd09d307fe31dc32d53d6c567723251b8d3278b06f49ee35fe6c8c2f3777c3d49b075b75f74dd5bf0c79c5ee09ee27fdaa654f27cf21a5c4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
